### ISSUE TITLE
Spaces?

### ISSUE THREAD

**Issue by blaines** [kylebragger/tiny#1]
Just want to confirm that the spaces are intentional, seems like they could be a problem under certain use cases...

ruby-1.8.7-p299 > Time.now.to_i
 => 1284101712 

ruby-1.8.7-p299 > Tiny::tiny(1284101712)
 => "t_ta e" 

ruby-1.8.7-p299 > Tiny::tiny_from_timestamp
 => "t_tat "

**Comment by kylebragger** [comment]
Did you run generate_set first? It generates the set of chars that goes here: http://cl.ly/c904aa24759b1ad7dd7f

**Comment by blaines** [comment]
I forgot that, the set and epoch would be useful in my issue...

  TINY_SET   = "nsZJ3A6vYCoi9tg2eGSzXNqhWcdEUrub8BkwOF4MKxljfI0yT175DmRpPHLaVQ"
  TINY_EPOCH = 1284101592

**Comment by kylebragger** [comment]
:)

**Comment by blaines** [comment]
The issue was closed? So are the spaces intentional or not? They seem like a problem to me...

**Comment by kylebragger** [comment]
yes, if you run generate_set and paste in the result into TINY_SET and TINY_EPOCH, it works as it should. you'll get spaces if you try to use the library without generating a set first.

**Comment by blaines** [comment]
But I did generate the set...
Not sure, maybe I just forgot to reload...

**Comment by kylebragger** [comment]
Did you paste it back into tiny.rb? Can you gist me the file?

**Comment by blaines** [comment]
Yea must be my error - somehow forgot to save or reload. :)

Maybe it would be helpful to make it fail with default values, it'd be more obvious that way.
